config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :book_authors
    has_many :books, through: :book_authors,dependent: :destroy
    validates :name, presence: true
    validates :birth_year, presence: true, numericality: true


end

app/models/book.rb
class Book < ApplicationRecord
    has_many :book_authors
    has_many :authors, through: :book_authors

end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/bookauthor.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController


    def index
        @authors = Author.all 
    end 

    def new
        @author = Author.new
    end

    def create
        @author = Author.new(author_params)
        if @author.save
            redirect_to @author
        else
            render :new
        end 
    end

    def show
        @author = Author.find(params[:id])
        
        
    end

    def edit
        @author = Author.find(params[:id])
    end

    def update
        @author = Author.find(params[:id])
        if @author.update(author_params)
            redirect_to @author
        else
            render :edit
        end 
    end

    def destroy
        @author = Author.find(params[:id])
        @author.destroy
        redirect_to authors_path
    end




    private

    def author_params
        params.require(:author).permit(:name, :birth_year)
    end



end

app/controllers/book_authors_controller.rb
class BookAuthorsController < ApplicationController


    

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @books = Book.all
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.create(book_params)
        redirect_to @book
    end

    def show
        @book = Book.find(params[:id])
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        @book.authors << Author.find(params[:book][:authors])
        redirect_to @book
    end

    def destroy
        
        @book = Book.find(params[:id])
        @author = Author.find(params["author"].keys[0])
        @book_author = BookAuthor.find_by(author_id: @author, book_id: @book)
        @book_author.destroy
        redirect_to @book
    end

    private

    def book_params
        params.require(:book).permit(:title, :pages, :authors)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
1. <%= link_to "Authors Index", authors_path%> </br>
2. <%= link_to "Books Index", books_path%>

app/views/authors/_submit_form.html.erb
<%= form_for @author do |f| %>
<%= f.label :name, 'Name'%>
<%= f.text_field :name %>
</br></br>
<%= f.label :birth_year, 'Birth year'%>
<%= f.text_field :birth_year%>
</br></br>
<%= f.submit %>
<% end%>

app/views/authors/edit.html.erb
<%= render "form" %>

<h1> Edit <%= @author.name %> </h1>

<ul>
<% if @author.errors.any? %>


  <% @author.errors.full_messages.each do |msg| %>
<li>
  <%= msg %>
  <% end %>
  </li>
<% end %>
</ul>

<%= render "submit_form"%>

app/views/authors/index.html.erb
<%= render "form" %>


<h1> Authors! </h1>

<a href="/authors/new"> New Author </a>

<ul>
<% @authors.each do |author|%>
<li>
<%= link_to author.name, author%> (b. <%=author.birth_year%>)

</li>


<% end %>
</ul>

app/views/authors/new.html.erb
<%= render "form" %>




<h1> New Author </h1>
<ul>
<% if @author.errors.any? %>

<li>
  <% @author.errors.full_messages.each do |msg| %>
  <%= msg %>
  <% end %>
  </li>
<% end %>
</ul>



<%= render "submit_form" %>

app/views/authors/show.html.erb
<%= render "form" %>

<h1> <%=@author.name%> (b. <%= @author.birth_year%>) </h1>



 <% if @author.books.empty? %>
   Books: <i> (none) </i>
   </br>
<% else %>
<p> Books: </p>
<ul>
<% @author.books.each do |books| %>
  

<li>
  <%= link_to books.title, books%>
</li>
    <%end%>
</ul>
<% end %>
 
<%= link_to "Edit #{@author.name}", edit_author_path %>
<%= form_tag author_path(@author.id), method: "delete" do %>
  <%= submit_tag "Delete #{@author.name}" %>
<% end %>

app/views/books/_form.html.erb
1. <%= link_to "Authors Index", authors_path%> </br>
2. <%= link_to "Books Index", books_path%>

app/views/books/index.html.erb
<%= render "form" %>


<h1>Books!</h1>
<ul>
    
    <% @books.each do |book| %>
    <li>
    <%= link_to "#{book.title} (#{book.pages} pages)", book_path(book) %>
    </li>

<% end %>
</ul>

app/views/books/show.html.erb
<%= render "form" %>

<h1><%= @book.title%> (<%=@book.pages%> pages)</h1>

<h2>Authors: </h2>
<ul>
<% @book.authors.each do |author| %>
<li>
<%= link_to "#{author.name} b. (#{author.birth_year})" , author_path(author) %>



<%= form_tag book_path(@book.id), method: "delete" do %>
  <%= submit_tag "Remove #{author.name}", :name => "author[#{author.id}]" %>
<%end%>

</li>
<%end%>
</ul>

<%= form_for @book do |f| %>
<%= f.collection_select :authors, Author.all, :id, :name %>
<%= f.submit%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIsFun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>